backend:
  name: github
  repo: bloom-works/coram-11ty
media_folder: "src/static/img"
public_folder: "/static/img"
publish_mode: 'editorial_workflow'

# Please run "npx @staticcms/proxy-server" for local backend
local_backend: true

# publish_mode: editorial_workflow
collections:
- label: 'Recommendations, Topics, and Tags'
  name: 'recommendationsTopicsTags'
  files:
    - label: 'Topics Collection'
      name: 'topicsCollection'
      file: 'src/_data/topics.yml'
      fields:
        - label: 'Topics'
          name: 'topics'
          widget: 'list'
          summary: '{{fields.title}}'
          fields:
            - {
                label: 'Title for url',
                name: 'title',
                widget: 'string',
                hint: 'Use dashes (-) instead of spaces ( ) to separate words.',
              }
            - label: 'Hero'
              name: 'hero'
              widget: 'object'
              fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - {
                    label: 'Image',
                    name: 'image',
                    widget: 'image',
                    media_folder: '/src/images/heros',
                    allow_multiple: false,
                  }
                - {
                    label: 'Background Color',
                    name: 'backgroundColor',
                    widget: 'select',
                    options:
                      ['primary', 'secondary', 'info', 'light', 'white'],
                    default: ['light'],
                  }
                - {
                    label: 'Image Alt Text',
                    name: 'imgAlt',
                    widget: 'string',
                  }
            - {
                label: 'Icon',
                name: 'image',
                widget: image,
                media_folder: '/src/images/topics',
                allow_multiple: false,
                hint: 'Must be an svg file type',
                pattern:
                  [
                    '.svg',
                    'Detected file type was not .svg. File type must be .svg',
                  ],
              }
            - { label: 'About this topic', name: 'about', widget: 'markdown' }
            - { label: 'Why this matters', name: 'why', widget: 'markdown' }
            - { label: 'What we can do', name: 'what', widget: 'markdown' }
            - {
                label: 'layout',
                name: 'layout',
                widget: 'hidden',
                default: 'topic',
              }
            - {
                label: 'Projects',
                name: 'projects',
                collection: 'projects',
                widget: 'relation',
                multiple: true,
                value_field: 'projects.*.title',
                search_fields: ['projects.*.title'],
                file: 'projects',
                required: false,
              }
            - label: 'Tags'
              name: 'tags'
              collection: 'recommendationsTopicsTags'
              widget: 'relation'
              multiple: true
              value_field: 'tags.*.title'
              search_fields: ['tags.*.title']
              file: 'tagsCollection'
              required: false
    - name: 'projects'
      label: 'Projects'
      file: 'src/_data/projects.yml'
      fields:
        - label: 'Projects'
          name: 'projects'
          widget: 'list'
          summary: '{{fields.title}}'
          fields:
            - {
                label: 'Title for url',
                name: 'title',
                widget: 'string',
                hint: 'Use dashes (-) instead of spaces ( ) to separate words.',
              }
            - {
                label: 'Title for heading',
                name: 'heading',
                widget: 'string',
              }
            - {
                label: 'About this recommendation',
                name: 'about',
                widget: 'markdown',
              }
            - { label: 'How to do this', name: 'how', widget: 'markdown' }
            - {
                label: 'Costs',
                name: 'costs',
                widget: 'list',
                field: { label: 'Cost', name: 'cost', widget: 'string' },
                summary: '{{fields.cost}}',
              }
            - {
                label: 'Benefits',
                name: 'benefits',
                widget: 'list',
                field:
                  { label: 'Benefit', name: 'benefit', widget: 'string' },
                summary: '{{fields.benefit}}',
              }
            - {
                label: 'Outcome Data',
                name: 'outcome',
                widget: 'markdown',
                required: false,
              }
            - label: "Who's doing this"
              name: 'who'
              widget: 'object'
              fields:
                - {
                    label: 'Number of States & Territories',
                    name: 'number',
                    widget: 'number',
                    value_type: 'int',
                    max: 54,
                    required: false,
                  }
                - {
                    label: 'Map Image',
                    name: 'image',
                    widget: 'image',
                    media_folder: '/src/images/recommendations',
                    required: false,
                  }
                - {
                    label: 'What are people doing',
                    name: 'what',
                    widget: 'markdown',
                    required: false,
                  }
            - {
                label: 'Get inspiration',
                name: 'inspiration',
                widget: 'markdown',
                required: false,
              }
            - {
                label: 'Summary for topic',
                name: 'summaryForTopic',
                widget: 'markdown',
                required: false,
              }
            - {
                label: "What's Needed",
                name: 'need',
                widget: 'markdown',
                required: false,
              }
            - label: 'Tags'
              name: 'tags'
              collection: 'recommendationsTopicsTags'
              widget: 'relation'
              multiple: true
              value_field: 'tags.*.title'
              search_fields: ['tags.*.title']
              file: 'tagsCollection'
              required: false
    - label: 'Tags Collection'
      name: 'tagsCollection'
      file: 'src/pages/content/tags.content.yml'
      fields:
        - label: 'Tags'
          name: 'tags'
          widget: 'list'
          summary: '{{fields.title}}'
          fields:
            - { label: 'Title', name: 'title', widget: 'string' }
- name: 'pages'
  label: 'Pages'
  files:
    - label: 'Main Page'
      name: 'index'
      file: 'src/_data/home.yml'
      fields:
        - label: 'Home'
          name: 'home'
          widget: 'object'
          fields:
            - label: 'Hero'
              name: 'hero'
              widget: 'object'
              fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - {
                    label: 'Image',
                    name: 'image',
                    widget: 'image',
                    media_folder: '/src/images/heros',
                    allow_multiple: false,
                  }
                - {
                    label: 'Image Alt Text',
                    name: 'imgAlt',
                    widget: 'string',
                  }
            - label: 'Topics'
              name: 'topics'
              widget: 'object'
              fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'Content', name: 'content', widget: 'string' }
                - { label: 'Link', name: 'link', widget: 'string' }
                - { label: 'Link Text', name: 'linkText', widget: string }
                - {
                    name: 'featured_topics',
                    label: 'Featured Topics',
                    widget: 'relation',
                    collection: 'topicsCollection',
                    search_fields: ['title'],
                    value_field: 'title',
                    display_fields: ['title'],
                  }
            - label: 'Features'
              name: 'features'
              widget: 'object'
              fields:
                - {
                    label: "What's new",
                    name: 'whatsNew',
                    widget: 'markdown',
                    required: false,
                  }
                - label: 'Large Feature'
                  name: 'largeFeature'
                  widget: 'object'
                  fields:
                    - { label: 'Title', name: 'title', widget: 'string' }
                    - {
                        label: 'Content',
                        name: 'content',
                        widget: 'markdown',
                      }
                    - {
                        label: 'Image',
                        name: 'image',
                        widget: 'image',
                        media_folder: '/src/images/features',
                        allow_multiple: false,
                      }
                    - {
                        label: 'Image Alt Text',
                        name: 'imgAlt',
                        widget: 'string',
                      }
                    - { label: 'Link', name: 'link', widget: 'string' }
                    - { label: 'Link Text', name: 'linkText', widget: string }
                    - {
                        label: 'Layout',
                        name: 'layout',
                        widget: 'hidden',
                        default: 'lg',
                      }
                - label: 'Small Features'
                  name: 'smallFeature'
                  widget: 'list'
                  fields:
                    - { label: 'Title', name: 'title', widget: 'string' }
                    - {
                        label: 'Content',
                        name: 'content',
                        widget: 'markdown',
                      }
                    - {
                        label: 'Image',
                        name: 'image',
                        widget: 'image',
                        media_folder: '/src/images/features',
                        allow_multiple: false,
                      }
                    - {
                        label: 'Image Alt Text',
                        name: 'imgAlt',
                        widget: 'string',
                      }
                    - { label: 'Link', name: 'link', widget: 'string' }
            - label: 'Our mission'
              name: 'mission'
              widget: 'object'
              fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'Content', name: 'content', widget: 'markdown' }
                - {
                    label: 'Image',
                    name: 'image',
                    widget: 'image',
                    media_folder: '/src/images/heros',
                    allow_multiple: false,
                  }
                - {
                    label: 'Image Alt Text',
                    name: 'imgAlt',
                    widget: 'string',
                  }
                - { label: 'Link', name: 'link', widget: 'string' }
                - { label: 'Link Text', name: 'linkText', widget: string }
    - label: 'About Page'
      name: 'about'
      file: 'src/pages/about.content.yml'
      fields:
        - label: 'Hero'
          name: 'hero'
          widget: 'object'
          fields:
            - { label: 'Title', name: 'title', widget: 'string' }
            - {
                label: 'Image',
                name: 'image',
                widget: 'image',
                media_folder: '/src/images/heros',
                required: false,
                allow_multiple: false,
              }
            - {
                label: 'Background Color',
                name: 'backgroundColor',
                widget: 'select',
                options: ['primary', 'secondary', 'info', 'light', 'white'],
                default: ['light'],
              }
            - {
                label: 'Image Alt Text',
                name: 'imgAlt',
                widget: 'string',
                required: false,
              }
        - label: 'About'
          name: 'about'
          widget: 'markdown'
        - label: 'Membership'
          name: 'membership'
          widget: 'markdown'
        - label: 'How it Works'
          name: 'howItWorks'
          widget: 'markdown'
        - label: 'Benefits of Membership'
          name: 'benefitsOfMembership'
          widget: 'markdown'
        - label: 'Current Members'
          name: 'currentMembers'
          widget: 'markdown'
        - label: 'Free Licensing Evaluation'
          name: 'freeEvaluation'
          widget: 'markdown'
